### ISSUE TITLE
[BUG]当设置结束日期为23:59:59时拖动滑块，日期会自动增加

### ISSUE THREAD

**Issue by Charbo23** [xpyjs/gantt#101]
默认情况下滑块的最终日期是0点，导致滑块无法覆盖最后一天，所以我初始化数据时将滑块的结束日期改为了23:59:59，展示上没有问题。
按住滑块中间位置进行拖动时，正常是将日期整体移动，日期间隔不变，但上述情况下，拖动会导致鼠标按下时日期立即增加了1天，拖动过程中是正常，再次按下又会增加1天
详见下图：
![甘特图bug](https://github.com/xpyjs/gantt/assets/26688564/11e98f3b-9541-4400-8855-120d70f7d100)

**Comment by jeremyjone** [comment]
update to v2.1.10

确实，因为移动时，我复用的左右方法，它们分别判断的，导致了这个问题

**Comment by Charbo23** [comment]
好的，非常感谢

> update to v2.1.10
> 
> 确实，因为移动时，我复用的左右方法，它们分别判断的，导致了这个问题
