### ISSUE TITLE
[BUG]设置move-by-unit后滑块拖动会存在偏离

### ISSUE THREAD

**Issue by RicardoWL** [xpyjs/gantt#104]
设置move-by-unit后，根组件unit使用默认的day，进行滑块拖动时，会出现偏离
![bug](https://github.com/xpyjs/gantt/assets/42986888/016656b2-3e72-4647-b68c-157c15e56ba0)

**Comment by RicardoWL** [comment]
增加了1天是因为我在滑动结束后将开始日期和结束日期分别设置为0点和23点59分59秒，来覆盖准确的日周期范围

**Comment by jeremyjone** [comment]
#101 是不是这个问题？

**Comment by RicardoWL** [comment]
应该不一样吧，那个是点击时候就增加了，这个是拖动过程偶尔出现，而且我已经更新到最新的2.1.10版本了

**Comment by jeremyjone** [comment]
了然。有时间我看一下
