### ISSUE TITLE
能否支持配置是否显示【日/周】这类的单位？

### ISSUE THREAD

**Issue by RicardoWL** [xpyjs/gantt#106]
滑动区域的表头能否支持配置是否显示【日/周】这类的单位？
![image](https://github.com/xpyjs/gantt/assets/42986888/970e63d1-fc5a-4333-8438-7d627c102227)

**Comment by jeremyjone** [comment]
不支持。因为这是dayjs配置的。我就是引用了一下

**Comment by RicardoWL** [comment]
我看了项目源码，是这里进行的日期格式化，如果格式化用.format('D')将不会带上单位。能否加配置这里是否带上o?
![image](https://github.com/xpyjs/gantt/assets/42986888/f4bf17f8-4e19-4c0d-bd05-8f29f12a52dd)

**Comment by jeremyjone** [comment]
我瞅瞅，忘了😂
