### ISSUE TITLE
[BUG]  UI freezes with large dataset

### ISSUE THREAD

**Issue by tesla-cat** [xpyjs/gantt#107]
- with the following large dataset the UI freezes (renders after a very long time):
- and seems the problem is with preprocessing

[ganttData (1).json](https://github.com/user-attachments/files/15986949/ganttData.1.json)

![1719399996022](https://github.com/xpyjs/gantt/assets/28215638/cafbea9a-5ab6-4a1e-b7b5-e59697015e89)

![1719400037861](https://github.com/xpyjs/gantt/assets/28215638/6a4969b4-c182-4713-a42d-52fe21dc7065)

**Comment by jeremyjone** [comment]
no one can render 10w+ rows in a flash

**Comment by tesla-cat** [comment]
i believe there is definitely room to improve

my own virtual table component renders the same dataset in a flash

i believe you also use virtual rendering under the hood right?

**Comment by jeremyjone** [comment]
If you can, I look forward to you can submit a pr to help it do better😊

**Comment by tesla-cat** [comment]
@jeremyjone 


but may i know if you are using virtual rendering already or not 😂

**Comment by jeremyjone** [comment]
I do not have this requirement, max the number of 10,000 rows I used. More optimization, I do not need, there is no need to update. You can pr and improve this component. hhhhhhh😁

**Comment by jeremyjone** [comment]
I used vir render, but its code by myself

**Comment by tesla-cat** [comment]
@jeremyjone 

turns out I made a mistake in my initial problem statement, there are only 12,000 tasks in this data, it is not a big dataset.

**Comment by tesla-cat** [comment]
@jeremyjone 

turns out I made a mistake in my initial problem statement, there are only ~ 12,000 tasks in this data, it is not a big dataset.

### and i found that the main issue is with 11,330 links, (it renders immediately if I remove the links), are you also virtual rendering the links?

### 我发现主要问题是 11,330 个 links 的渲染， 去掉links 后渲染很顺畅， links 也有使用 虚拟渲染吗

can you please reopen the issue?
