### ISSUE TITLE
[BUG]已渲染范围的第一天和最后一天未正常渲染节假日

### ISSUE THREAD

**Issue by RicardoWL** [xpyjs/gantt#109]
已渲染范围的第一天和最后一天未正常渲染节假日
图中6月29与30日为周末，如果是渲染范围的最后一天，则未正常渲染节假日样式

![bug_2](https://github.com/xpyjs/gantt/assets/42986888/ed01cfe6-df17-42ac-9b0f-ccaf493191fa)

**Comment by jeremyjone** [comment]
代码我看一下
