### ISSUE TITLE
[FEATURE]希望左侧表格列能够进行宽度限制后自由滚动

### ISSUE THREAD

**Issue by AlphaYoung111** [xpyjs/gantt#116]
![image](https://github.com/xpyjs/gantt/assets/54132313/fe24cffe-035a-4010-a6bb-4164435bdf86)
希望能够实现像上图这样固定左侧的表格区域，我的表格列数是动态的，所以希望能够固定宽度，然后自由横向滚动

**Comment by jeremyjone** [comment]
这样做本身有问题，它不是表格，也不应该当做表格使用

**Comment by huoqingzhu** [comment]
我现在同样的需求，希望可以采纳！

**Comment by jeremyjone** [comment]
你可以fork自行实现它。我不会实现这个需求，因为它和组件本身需求设计有冲突，希望理解

我在issue和文档中一再强调，不要把左侧表格当做普通表格使用，因为这和甘特图本身就会有思想上的冲突，我们应当使用它展示必要条件，而不是全量信息。

或许上面这个我的设计思路和您的现有需求不符，但我还是认为这应该是一个正确使用甘特图的方式：尽可能多的展示时间区间，而不是表格信息，否则我们直接改造 element 的表格就完全够用啦

**Comment by AlphaYoung111** [comment]
那是否能暴露一个左侧表格的插槽交由开发自己去自定义，这样依然是展示右侧时间图作为主体，但是也能够自定义左侧

**Comment by xpyjs** [comment]
不可以，因为里面表格部分引用的比较多，插槽自定义容易错乱，需要考虑很多边界情况。如果你很需要，可以foek后针对自己项目二次开发
