### ISSUE TITLE
[FEATURE] unit 希望新增年的时间单位

### ISSUE THREAD

**Issue by v833** [xpyjs/gantt#121]
unit 希望新增年的时间单位

**Comment by jeremyjone** [comment]
年跨度太大，对于甘特图没有具象意义。年度任务应当是类似列表，而不是进度

**Comment by v833** [comment]
> 年跨度太大，对于甘特图没有具象意义。年度任务应当是类似列表，而不是进度

我做的业务需要以年为时间跨度，我想fork一份代码，自己加一下年的时间单位，请问加时间单位有什么需要注意的点吗？

**Comment by v833** [comment]
> @v833 配好对应宽度就可以啦，其他没有啥

好的，感谢
