### ISSUE TITLE
[FEATURE]能否添加一个甘特图绘图区域背景色随日期可以显示不同背景色的功能

### ISSUE THREAD

**Issue by fengxc** [xpyjs/gantt#129]
比如说，项目进行到某一个时期，比较重要，背景色深一些，下一个时间段是维护阶段，所以浅一些之类的，目前只能区分工作日和假日自定义颜色，不够灵活，最好每一列都能定义背景色样式，甚至每一行每一列都能定义样式？

**Comment by jeremyjone** [comment]
你可以自定义节假日呀。把你觉得重要的日子设为节假日的状态，就可以自定义对应日期的背景色了

**Comment by fengxc** [comment]
但是节假日是不是只能维护一组？如果我想多个组有什么好的办法支持嘛

**Comment by jeremyjone** [comment]
@fengxc [文档](https://xpyjs.github.io/gantt/docs/root.html#holidays)
