### ISSUE TITLE
[BUG]当时间轴单位是周的时候右侧图形区第一列格子的表头不完整

### ISSUE THREAD

**Issue by fengxc** [xpyjs/gantt#130]
当时间轴单位是周的时候右侧图形区第一列格子的表头不完整，看起来只露出了一天导致格子里面字是压缩了的
![屏幕截图 2024-08-21 001641](https://github.com/user-attachments/assets/a1f98dc2-0ffe-4f00-87e2-1664031a802f)

**Comment by jeremyjone** [comment]
它本来也不是完整的，只有一天
