### ISSUE TITLE
[FEATURE]有增加前置计划功能的打算不？

### ISSUE THREAD

**Issue by mfkwgizhoujian** [xpyjs/gantt#21]
控件好久没更新了，会考虑增加前置计划功能不？

**Comment by jeremyjone** [comment]
@mfkwgizhoujian 工作较忙，目前内容符合我的使用，就没动。后续一定会持续更新。

你的建议，可否展开说说？如果合适，我考虑一下

**Comment by mfkwgizhoujian** [comment]
> @mfkwgizhoujian 工作较忙，目前内容符合我的使用，就没动。后续一定会持续更新。
> 
> 你的建议，可否展开说说？如果合适，我考虑一下

我看你新的版本拖动父节点，当开始时间晚于子节点的时候，子节点的开始时间也会自动调整，那么如果一个任务设置了前置任务，我这个任务的开始时间必须在前置任务的结束时间之后，当拖动调整时间时，也会自动的进行调整，同时右边的图形可以有一根曲线连接这两个任务，能一眼看出是有前置关系。

**Comment by jeremyjone** [comment]
@mfkwgizhoujian 线其实我已经画了，只是还在调试，你说的这个在计划中的，等一下吧😃
