### ISSUE TITLE
vue 2 和vue3 相差大吗

### ISSUE THREAD

**Issue by Messilimeng** [xpyjs/gantt#24]
你好我们的项目已经定了用vue2 但是想用您的组件 ，想问一下 vue2 和vue3 实现的效果相差大吗  ，vue2 能实现像demo 一样的效果吗

**Comment by jeremyjone** [comment]
有以下几点吧，使用上来说：

- vue2可能对于大数据（1w+）会卡一些，vue3目前测试不存在这个问题。
- vue3的有一些新功能，可以参看更新日志。vue2的功能相对于v1.0版本是基本一样的，之后的新功能可能只有vue3有。

另外：
- vue3相比vue2内部的所有逻辑都是重新写的
- vue3使用了系统的响应式，vue2是基于Proxy自己写的响应

其他好像也没什么了。总体来说，vue2版本目前处于可用，修复问题但不更新的状态。vue3会持续有新功能上线。

这个确实是我的问题，一开始没想那么多，因为是自己用的，所以就直接升级了版本。我在考虑新建一个包，将vue2和vue3分开。

实在有需求的话，也欢迎pr。

**Comment by Messilimeng** [comment]
所以看到vue2 版本的demo 好简陋 怕最终无法实现效果，导致浪费时间

**Comment by jeremyjone** [comment]
@Messilimeng 可以先试一下，如果够用的话，那就最好啦。如果不行，可以pr，或者提需求也行，我看时间先把两个版本拆一下，然后再更新

**Comment by Messilimeng** [comment]
@jeremyjone 好的非常感谢

**Comment by Messilimeng** [comment]
@jeremyjone 你好请问如何和你取的联系呢，有点事想和你沟通一下(*￣︶￣)

**Comment by jeremyjone** [comment]
有事可以直接在这里问哈~我看到会及时回的

**Comment by jeremyjone** [comment]
呃，可以发邮件到 jeremyjone@qq.com

**Comment by Messilimeng** [comment]
@jeremyjone 已发

**Comment by Messilimeng** [comment]
@jeremyjone  有进展吗哈哈

**Comment by jeremyjone** [comment]
@Messilimeng 哈哈哈，这个月有点忙，还真没弄呢。我只把vue2版本的给单提成一个库，区别于这个库

**Comment by Messilimeng** [comment]
@jeremyjone 老哥啥状况了哦

**Comment by jeremyjone** [comment]
@Messilimeng 😂😂😂不要催，这阵子一直在加班，没时间弄

**Comment by Messilimeng** [comment]
@jeremyjone 没催 就是关心你一下

**Comment by jeremyjone** [comment]
@Messilimeng 谢谢哈，我有时间尽快弄一下。最近手头事儿有点多。年中了嘛

**Comment by XiaoPiHong** [comment]
> 你好我们的项目已经定了用vue2 但是想用您的组件 ，想问一下 vue2 和vue3 实现的效果相差大吗 ，vue2 能实现像demo 一样的效果吗



> 有以下几点吧，使用上来说：
> 
> * vue2可能对于大数据（1w+）会卡一些，vue3目前测试不存在这个问题。
> * vue3的有一些新功能，可以参看更新日志。vue2的功能相对于v1.0版本是基本一样的，之后的新功能可能只有vue3有。
> 
> 另外：
> 
> * vue3相比vue2内部的所有逻辑都是重新写的
> * vue3使用了系统的响应式，vue2是基于Proxy自己写的响应
> 
> 其他好像也没什么了。总体来说，vue2版本目前处于可用，修复问题但不更新的状态。vue3会持续有新功能上线。
> 
> 这个确实是我的问题，一开始没想那么多，因为是自己用的，所以就直接升级了版本。我在考虑新建一个包，将vue2和vue3分开。
> 
> 实在有需求的话，也欢迎pr。

要是支持24小时就好了

**Comment by jeremyjone** [comment]
@XiaoPiHong 逻辑上支持到毫秒，因为我没判断日期界限。只是没有显示而已

**Comment by Messilimeng** [comment]
666 小声的问一句 v2有进展了吗？

**Comment by jeremyjone** [comment]
@Messilimeng 写了一部分，进度颇慢😂

**Comment by Messilimeng** [comment]
我已经迫不及待了 是不是要竣工了 激动 @jeremyjone

**Comment by jeremyjone** [comment]
@Messilimeng 差不多了，还差点调试。

**Comment by Messilimeng** [comment]
@jeremyjone  辛苦了， 等待是值得的。 (*￣︶￣)

**Comment by Messilimeng** [comment]
@jeremyjone  请问什么时候可以测试啊

**Comment by jeremyjone** [comment]
卡在了一个奇怪的bug上🤣一个礼拜了……

**Comment by Messilimeng** [comment]
好的呢 啥时候能好啊o(╥﹏╥)o

**Comment by jeremyjone** [comment]
这几天搞出来了。调一下 bug，应该就可以测试使用了~

**Comment by Messilimeng** [comment]
好的非常感谢，好好完善一下 ，最近我忙其他的，昨晚就是整这个模块
