### ISSUE TITLE
数据过多需要滚轮滑动时出现渲染错误

### ISSUE THREAD

**Issue by 2657615334** [xpyjs/gantt#27]
**Is your feature request related to a problem? Please describe.**
当数据过多，滚轮下滑时会出现一堆空数据，请问怎么解决（需要代码我可以发你），还有现在文档看不了了。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xpyjs** [comment]
文档已经可以了。

数据过多？您的数据量是多少？请重现问题

**Comment by 2657615334** [comment]
就是我们项目需要每一行有两条数据（两个起止时间在一排上，可以重叠）。然后我就把右边父级给隐藏掉，然后把左边的两个子级给隐藏掉，然后用类名定位，将两个子级定位到父级的那一排上面，在滚轮不翻页的情况下展示正常，当滚轮往下滑动到达第二页时，数据就出现混乱

**Comment by xpyjs** [comment]
请重现问题

**Comment by xpyjs** [comment]
请重现问题

**Comment by 2657615334** [comment]
[xGantt.zip](https://github.com/xpyjs/gantt/files/8963179/xGantt.zip)

**Comment by 2657615334** [comment]
直接看看代码吧

**Comment by 2657615334** [comment]
![gt1](https://user-images.githubusercontent.com/93808886/175199017-915a8840-fdb9-4e6d-92fa-63a7bfdabf88.png)
![gt2](https://user-images.githubusercontent.com/93808886/175199025-842c2045-b6cd-4829-a016-7b0e68c8277a.png)
![gt3](https://user-images.githubusercontent.com/93808886/175199047-7bc4579b-f490-474a-a425-2b7ab4c085f3.png)
![QQ截图20220623110844](https://user-images.githubusercontent.com/93808886/175199073-2d28278a-f998-48c7-a682-701beae574b4.png)

**Comment by xpyjs** [comment]
@2657615334  我看了一眼你的代码。

- 首先，我非常不建议你这么写。

- 其次，针对你提到的问题，没有数据不是渲染错误，而是你压根没有给数据。
    你所有能够渲染出的数据，都是 `index` 为单号的，而渲染不出数据，则 `index` 都是 `x-x` 格式的，这些内容的 `planOrderInfo` 字段，你压根没给数据，当然返回 `NaN`，并没有问题。

- 最后，并不是你所说的滚动到下面就出问题，而是当渲染的顶部首条内容如果是单号 `index`，则不会出问题，如果为 `x-x` 格式的 `index` 都会出问题，问题在于你的数据不全，而不是组件有问题。如果你把 class 中的 `display:none` 去掉，会看到你想隐藏掉的行，都是 `NaN`。

**Comment by 2657615334** [comment]
这样写的目的就是，想让两个子级显示到一排上
