### ISSUE TITLE
[FEATURE]同一任务多个滑块需求

### ISSUE THREAD

**Issue by yanzubenyan** [xpyjs/gantt#28]
应用场景：项目进度有计划开始时间还有计划结束时间，所以存在实际开始时间和实际结束时间，需要对比两者的时间差，所以同一任务需要显示两个滑块

**Comment by xpyjs** [comment]
目前没有相关计划。参考之前 #17 和 #4 。

**Comment by xpyjs** [comment]
不过我个人认为，有两个方式：

1、可以通过进度来展示。
2、用两行来做同一个事情，第一行作为计划，第二行作为实际。重载一下第二行的表格即可。

第二个效果应该可以达到你的要求。

**Comment by yanzubenyan** [comment]
在提问之前我也考虑过通过新增一行来解决问题，是可行的，只是展示没那么好看，我提出这个问题的原因是因为有些项目计划开始时间和实际开始时间是不一样的，分析项目情况的时候就需要对比这种差异，所以百分比这种不太适应。

**Comment by jeremyjone** [comment]
了解。但目前确实不支持这种做法，如果做这个，可能需要大版本修改。

**Comment by yanzubenyan** [comment]
我先用新增一行来解决这个问题吧，期待项目做的越来越好

**Comment by jeremyjone** [comment]
谢谢关注

**Comment by xpyjs** [comment]
#45
