### ISSUE TITLE
[BUG]vue2版本的和elementUI的表格有冲突 会导致表格文本内容消失

### ISSUE THREAD

**Issue by lzyllp** [xpyjs/gantt#30]
vue版本2.6.14
elemenUI版本2.15.9
@xpyjs/gantt-vue2 1.0.1

![image](https://user-images.githubusercontent.com/2051954/187580549-9f3f69f4-122f-40a9-805d-47e45bde1602.png)

**Comment by jeremyjone** [comment]
复现代码？
