### ISSUE TITLE
[FEATURE]添加支持通过拖拽关联任务，展示任务依赖关系线

### ISSUE THREAD

**Issue by c2012y** [xpyjs/gantt#32]
任务之间的依赖关系主要有以下四种：

- Finish to Start (FS)​ — 结束到开始，即A任务必须先结束，B任务才能开始。这是最常见的一种依赖关系。
- Start to Start (SS) — 开始到开始，即A任务必须先开始，B任务才能开始。
- Finish to Finish (FF) — 结束到结束，即A任务必须先结束，B任务才能结束。
- Start to Finish (SF) — 开始到结束，即A任务必须先结束，B任务才能结束。
- 
![image](https://user-images.githubusercontent.com/10131502/230385247-f7177f7a-fd51-46f0-a13f-bc4fef249f09.png)

**Comment by jeremyjone** [comment]
很好的提议

**Comment by c2012y** [comment]
> 很好的提议

这个有实现的计划吗 ？(*￣︶￣)

**Comment by jeremyjone** [comment]
#21

**Comment by jeremyjone** [comment]
#21
