### ISSUE TITLE
我可不可以直接在甘特图上直接拖动创建一个时间范围

### ISSUE THREAD

**Issue by jeremyjone** [xpyjs/gantt#35]
还想问一个问题，我可不可以直接在甘特图上直接拖动创建一个时间范围。目前好像必须要求有开始和结束时间才显示滑块，
我某些情况下没开始和结束时间，想直接拖动创建一个出来

![VeryCapture_20230510171544](https://github.com/xpyjs/gantt/assets/50822851/c6b132b0-695a-49a9-9dd6-95bcb7ec551f)

类似这个效果

_Originally posted by @iarthit in https://github.com/xpyjs/gantt/issues/34#issuecomment-1541637294_

**Comment by iarthit** [comment]
作者你好，请问下这个功能以后会实现吗

**Comment by jeremyjone** [comment]
@iarthit 新版吧，最近在写

**Comment by jeremyjone** [comment]
这个考虑了一下。因为日期初始需要添加，所以不需要该功能。

**Comment by iarthit** [comment]
要不再考虑考虑？这个功能还是挺实在的，能给项目增加亮点

**Comment by jeremyjone** [comment]
那需要看后续有没有可能将时间可选化。目前来说，时间如果一定有的话，那么这个长按拉时间的功能确实比较冲突，没有什么必要的。一定是在没有时间的情况下才可以这样操作，否则很容易误操作，还需要考虑撤销的问题，对于来说，比较乱
