### ISSUE TITLE
[FEATURE] I added props for text. Please merge it

### ISSUE THREAD

**Issue by Nurymadil** [xpyjs/gantt#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nurymadil** [comment]
first i forked project. after i publish it with my changes. but i cant build. how to fix it. there many problems with find to function.  example. i dunno how fix it
<img width="738" alt="image" src="https://github.com/xpyjs/gantt/assets/54814137/b6be50e2-b414-43a6-9c5a-a53cf336ee99">

**Comment by jeremyjone** [comment]
I will remove drawer at v2.0

You can use any framework made it.
