### ISSUE TITLE
列组件中最后一个显示不出内容[BUG]

### ISSUE THREAD

**Issue by keshengtiquan** [xpyjs/gantt#38]
你好麻烦问下 XGanttColumn组件的最后一个显示不出来，是我配的有问题吗？
<img width="1561" alt="image" src="https://github.com/xpyjs/gantt/assets/87509407/afd7fade-de54-42e5-ad26-fa6391c03c89">

<img width="1393" alt="image" src="https://github.com/xpyjs/gantt/assets/87509407/fa17c847-2d52-4ed3-bcf5-2a513464100c">

**Comment by jeremyjone** [comment]
给我一个最小复现代码，我照着你的截图敲了一下，没有问题

**Comment by gukunruo** [comment]
我也是同样问题，同一串代码两个项目中跑，一个能正常展示，一个不展示最后一列，不知道为何？有解决办法吗？
<img width="819" alt="image" src="https://github.com/user-attachments/assets/cb8a4319-a1d1-4bcd-b5bf-41137596ca54">
