### ISSUE TITLE
[BUG] 当数据动态绑定以后，dataList的Length没变化，界面不刷新

### ISSUE THREAD

**Issue by light499960904** [xpyjs/gantt#41]
**Describe the bug**
清空DataList，重新赋值（数据长度一致），页面不变
![image](https://github.com/xpyjs/gantt/assets/27767203/15aad629-ffb8-4fee-a78f-bfeef84116c0)
![image](https://github.com/xpyjs/gantt/assets/27767203/3b8fa1b6-0dc8-4db9-a187-6a1f5a50163a)

**Comment by imlinhanchao** [comment]
发现得吧 data 置空，然后再 nextTick 设置才能正常刷新数据。比如这样：

```vue
data.value = [];
nextTick(() => {
      data.value = rsp,data;
});
```

而直接赋值则无法联动，比如：

```vue
data.value = rsp,data;
```

**Comment by jeremyjone** [comment]
参考 [demo](https://github.com/xpyjs/gantt/blob/master/demo/demo.vue) @imlinhanchao 

reactive 替换 ref 的方式我也试了，同样没有问题。如果还有问题，给我一个示例
