### ISSUE TITLE
[FEATURE]能否同一行有多条甘特图

### ISSUE THREAD

**Issue by LucidF** [xpyjs/gantt#45]

**Comment by xpyjs** [comment]
首先，就我个人而言，在我使用过程中没有遇到两条的需求。

其次，我认为一行多条违背了甘特的初衷。可能有些特殊需求确实需要，也有其他甘特组件支持，但就目前来说，我不确定这个功能是大多数人需要的。仅就我的认知来说，它不是必须的，所以我不会考虑这个需求。

如果一定需要，可以参考 #28 的解决方案，重写 slider 样式，或者改为多行。

**Comment by wonderfulliu** [comment]
> 首先，就我个人而言，在我使用过程中没有遇到两条的需求。
> 
> 其次，我认为一行多条违背了甘特的初衷。可能有些特殊需求确实需要，也有其他甘特组件支持，但就目前来说，我不确定这个功能是大多数人需要的。仅就我的认知来说，它不是必须的，所以我不会考虑这个需求。
> 
> 如果一定需要，可以参考 #28 的解决方案，重写 slider 样式，或者改为多行。

有这么一个场景：工厂中有多种设备，每种设备负责一道工序加工，一个订单的完成需要多道工序加工。在此基础上，以每一种设备为一行，那么该种设备在不同时间段会加工不同订单的同一工序，因此会产生同一行出现多条甘特图的情况。这个场景出现在工厂的智能化排产中。

**Comment by jeremyjone** [comment]
> > 首先，就我个人而言，在我使用过程中没有遇到两条的需求。
> > 其次，我认为一行多条违背了甘特的初衷。可能有些特殊需求确实需要，也有其他甘特组件支持，但就目前来说，我不确定这个功能是大多数人需要的。仅就我的认知来说，它不是必须的，所以我不会考虑这个需求。
> > 如果一定需要，可以参考 #28 的解决方案，重写 slider 样式，或者改为多行。
> 
> 有这么一个场景：工厂中有多种设备，每种设备负责一道工序加工，一个订单的完成需要多道工序加工。在此基础上，以每一种设备为一行，那么该种设备在不同时间段会加工不同订单的同一工序，因此会产生同一行出现多条甘特图的情况。这个场景出现在工厂的智能化排产中。

@wonderfulliu 你说的问题，和我们的使用方式差不多，我认为可以通过创建具有父子关系的多层级视图来处理。

Why：
1、单行单条能够很直观的展示时间（甘特图的主要作用）
2、具有父子关系的多行数据，可以有效拆分具体任务
3、如果同一行具有多段任务视图，有时候会导致显示不全而出现操作/计划失误（比如屏幕可以展示1个月，但是有多段，分别占位了3个月，那么会展示不全，有可能会导致用户操作出现偏差）

就你说的场景而言，一个设备在不同时段加工不同订单的同一工序，这种其实是不是应该根据订单进行拆分？如果是以设备为维度，可以将其作为父节点，不同订单作为子节点，这样看上去更加直观，而不是断续的

:)
