### ISSUE TITLE
[BUG] 当开始日期和结束日期是同一天的时候，甘特图的slider没有宽度，是不是应该有一格的宽度呀

### ISSUE THREAD

**Issue by kangxiangli** [xpyjs/gantt#48]
![1686114142365](https://github.com/xpyjs/gantt/assets/19146861/0feb3dee-a5f7-41e5-a10c-227bbd5eb177)
辛苦了  谢谢了

**Comment by jeremyjone** [comment]
你可以给结束日期一个最大日期，比如当天的23:59:59
