### ISSUE TITLE
后续可以添加一个基线对比的功能吗

### ISSUE THREAD

**Issue by MingMingDa** [xpyjs/gantt#50]
根组件中能不能添加一个基线对比数据的参数，用来添加基线数据的数组，基线只需要有对比效果就好了。
![image](https://github.com/xpyjs/gantt/assets/52748907/d68edb0c-21a1-4e19-a801-d9d77beb9ecc)

**Comment by jeremyjone** [comment]
没理解😢具体做什么。可以写个 demo，或者直接 pr

**Comment by jeremyjone** [comment]
这样的暂时不考虑
