### ISSUE TITLE
当前XGanttColumn插槽无法通过for循环创建，作者有没有想法改进一下

### ISSUE THREAD

**Issue by Lee-shung** [xpyjs/gantt#52]
想通过这种方式

`<x-gantt-column v-for="column in columns" :label="column.label" :width="column.width" :key="column.key"></x-gantt-column>
`

**Comment by jeremyjone** [comment]
`v-for` 是 vue 自带的功能，我不会也不能代替它。它对于 `gantt` 组件来说，属于原生属性，是天然支持的。你没有成功创建，可能是你得代码出现了问题。请检查代码。如果还有问题，可以贴过来我看一下

**Comment by Lee-shung** [comment]
`<script setup>
import { ref } from "vue";
import { XGantt, XGanttColumn } from '@xpyjs/gantt'
import '@xpyjs/gantt/dist/index.css';
const dataList = [
    {
        index: 1,
        startDate: "2023-06-05",
        endDate: "2023-08-20",
        name: "mydata1",
    },
    {
        index: 2,
        startDate: "2023-07-07",
        endDate: "2023-09-11",
        name: "mydata2",
        children: [
            {
                index: 3,
                startDate: "2023-07-10",
                endDate: "2023-08-15",
                name: "child1",
            }
        ]
    }
];
const columns = [
    {
        width: 120,
        name: '名称1',
        label: '名称',
        key: '1'
    },
    {
        width: 120,
        name: '时间',
        label: '名称1',
        key: '2'
    },

]
const unit = ref('day')
</script>`

`

<template>

    <div style="height: 600px">
        
        <x-gantt
            data-id="index"
            :data="dataList"
            :unit="unit"
            :row-height="40"
        >
            <x-gantt-column v-for="column in columns" :label="column.label" :width="column.width" :key="column.key">

                <template v-slot="{row}">
                    <span style="font-size: 14px">{{ row[column.name] }}</span>
                </template>
            </x-gantt-column>
        </x-gantt>

    </div>
</template>

`

**Comment by jeremyjone** [comment]
![image](https://github.com/xpyjs/gantt/assets/37676231/f9dfcfde-a68b-4ad8-bd3a-6321f5251287)

columns.length == 2，显示两个，没有问题呀？

**Comment by Lee-shung** [comment]
![image](https://github.com/xpyjs/gantt/assets/53204791/b49e1bc8-4503-4123-a28b-3ac74c2cde03)
奇了怪了，在我这确实不行，版本2.1.0，还有表头高度貌似设置没效果，还是默认的80

**Comment by xpyjs** [comment]
#68
