### ISSUE TITLE
[BUG]甘特图按月份展示时slider展示位置不正确

### ISSUE THREAD

**Issue by GeassAthena** [xpyjs/gantt#53]
**Describe the bug**
如图所示起始日期为4月28日，但是展示时出现在5月的位置，选择按天和按周展示时所属月份是正常显示的

**Expected behavior**
在正确的月份显示

**Screenshots**
![image](https://github.com/xpyjs/gantt/assets/40521247/511f9c20-72f1-4baa-8754-29a4dda346a5)

**Versions**
 - Version 2.0.4
 - Browser edge

**Comment by GeassAthena** [comment]
此外，表格头部的日、周展示格式是否可更改或者配置，2.04版本日的显示是纯数字，但是2.1.0版本变成类似于 1th 的展示形式，尝试过dayjs国际化，但是没有发生变化
![image](https://github.com/xpyjs/gantt/assets/40521247/a404ce37-d3c9-4f71-a7c3-480ac5263b9f)

**Comment by GeassAthena** [comment]
> 日期位置问题，给我复现代码
> 
> 表头内容问题，你可以看一下当前是什么语言：
> 
> ```js
> dayjs.locale('zh-cn');
> 
> console.log('main', dayjs.locale());
> ```

关于表头内容问题

![image](https://github.com/xpyjs/gantt/assets/40521247/67014d52-c39c-4832-b842-7d83e08cc8c9)

![image](https://github.com/xpyjs/gantt/assets/40521247/2ab93fe2-62ac-4aa0-83a6-28a0b34cb73f)

版本号 => "@xpyjs/gantt": "^2.1.0"

**Comment by Lee-shung** [comment]
![image](https://github.com/xpyjs/gantt/assets/53204791/c367dea9-a588-41c7-8a50-e3da84d2f9be)
我也一样 但是demo确实没问题

**Comment by GeassAthena** [comment]
> 日期位置问题，给我复现代码
> 
> 表头内容问题，你可以看一下当前是什么语言：
> 
> ```js
> dayjs.locale('zh-cn');
> 
> console.log('main', dayjs.locale());
> ```

关于日期位置

我将demo代码复制到项目中执行效果如下：

按月展示：![image](https://github.com/xpyjs/gantt/assets/40521247/01a3b670-a08d-4d5b-9fc9-5cae2f135322)

按天展示![image](https://github.com/xpyjs/gantt/assets/40521247/8a0f24f1-767a-49d8-817f-fbfde711ec26)

甘特图配置和demo中的一致，使用的数据为
```javascript
const ganttData = reactive([{
      index: '2',
      type: 1,
      startDate: new Date('2022-02-19'),
      endDate: new Date('2022-07-24'),
      children: [
        {
          index: '20000001',
          startDate: new Date('2022-03-09'),
          endDate: new Date('2022-07-17'),
          children: [
            {
              index: '2000000101',
              startDate: new Date('2022-03-09'),
              endDate: new Date('2022-07-17'),
              children: [],
            },
            {
              index: '2000000102',
              startDate: new Date('2022-03-09'),
              endDate: new Date('2022-06-19'),
              children: [],
            },
          ],
        },
      ],
    },
]);
```
