### ISSUE TITLE
[FEATURE] 作者 后期可否增加在关于时间开始 实际结束时间相关的功能

### ISSUE THREAD

**Issue by xiaohappyc** [xpyjs/gantt#55]
你好作者：
感谢你提供的gantt 给我们提供了很大的帮助
想问一下 以后会考虑增加 每一个task 的实际开始时间 实际结束时间的标识吗 在时间轴上展示

**Comment by jeremyjone** [comment]
这个问题只有有小伙伴提过，我的想法是暂不考虑这种方式。

首先，我认为这种方式是非常不好的，它会呈现出一种错乱的效果，感官上非常凌乱。我非常排斥同一行出现多条，无论什么原因。我知道现在市面上的大部分甘特图组件都可以同行多条，这导致了很多用户甚至在使用 excel 制作甘特图进度时，都习惯了一行多条，这其实为非常违背甘特初衷的。最直观的感受是：
- 1、乱
- 2、遇到重叠，会看不到全貌

其次，这种效果其实有其他方式替代。比如可以通过标色将不同状态如 `未完成`、`计划内`、`超期` 等标记为不同颜色，这个由使用者提供即可。同时我提供了百分比进度，可以一目了然当前干了多少，这个效果按照甘特图的作用来说，已经够用。

实在希望多条的，还可以通过多行实现效果，可以一行计划、一行实际。在 v2 版本中已经提供了连线，可以通过连线说明两者之间的关系。

总之呢，我是希望呈现一个干净整洁的甘特图效果，让使用者一目了然。
