### ISSUE TITLE
甘特图渲染会多出很多日期

### ISSUE THREAD

**Issue by 979680721** [xpyjs/gantt#58]
**Describe the bug**      
绑定后端返回的数据出现了问题，最早的开始日期是2023-09-06、最晚的结束日期是2023-10-10，但是渲染的时候日期一直持续到了2024-06，出现了很多空白日期，我是以月为时间间隔，如下图所示。
**Versions**
2.1.1
**Screenshots**
![image](https://github.com/xpyjs/gantt/assets/79731490/3815ed99-c373-40fe-bb61-6a8138b8122f)
![image](https://github.com/xpyjs/gantt/assets/79731490/ee82edd9-af9e-448f-ae2b-a80fd8a5ba70)

**Comment by jeremyjone** [comment]
那不然后面是空白的？😕

**Comment by jeremyjone** [comment]
宽度是固定的，所以无论怎么取，右侧都会取最大值而已
