### ISSUE TITLE
你好，我想请问一下，我这边拉下来的git项目，执行dts打包命令时报错了，这个是因为什么原因呢

### ISSUE THREAD

**Issue by MaybeWe** [xpyjs/gantt#62]
![image](https://github.com/xpyjs/gantt/assets/20982028/3696732e-faf4-4dfe-a4b5-69ced2b9fb9c)

**Comment by MaybeWe** [comment]
![image](https://github.com/xpyjs/gantt/assets/20982028/b0030855-3c53-4f9c-b622-60193c755a80)
@types/node也已经重新安装，还是报这个错误，是否是因为版本问题导致的

**Comment by jeremyjone** [comment]
如果你已经安装了 @types/node 模块，但仍然遇到了这个错误，可能是因为你的 tsconfig.json 文件中的配置有误。你可以检查一下 tsconfig.json 文件中的配置是否正确，或者尝试删除 node_modules 目录并重新安装依赖。
