### ISSUE TITLE
[FEATURE]请问有计划开发里程碑功能吗

### ISSUE THREAD

**Issue by sleepy-13** [xpyjs/gantt#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xpyjs** [comment]
没有这个计划。

一个简单的实现方式：可以自行设定进度样式，以适配对应的里程碑

**Comment by sleepy-13** [comment]
那可否在滑块上加一个自定义类名，可以接收行参数，根据不同类型作区分




睡虫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xpyjs/gantt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xpyjs/gantt] [FEATURE]请问有计划开发里程碑功能吗 (Issue #66)





 
没有这个计划。
 
一个简单的实现方式：可以自行设定进度样式，以适配对应的里程碑

**Comment by xpyjs** [comment]
参考 [文档](https://xpyjs.github.io/gantt/docs/slider.html#default)，可以直接重载

**Comment by sleepy-13** [comment]
好的&nbsp; 我试试&nbsp; 感谢大神。。。。。。。。。




睡虫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xpyjs/gantt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 晚上6:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xpyjs/gantt] [FEATURE]请问有计划开发里程碑功能吗 (Issue #66)





 
参考 文档，可以直接重载
