### ISSUE TITLE
[BUG] 按照文档走报错 无法进入页面

### ISSUE THREAD

**Issue by 2663272622** [xpyjs/gantt#70]
runtime-core.esm-bundler.js:3211 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')
![1111](https://github.com/xpyjs/gantt/assets/49867692/ffb1263b-8de7-4d69-bfdb-2d0b26b6f383)
![2222222222](https://github.com/xpyjs/gantt/assets/49867692/22e52775-2599-4823-aaab-2d921583e5d1)
![333333](https://github.com/xpyjs/gantt/assets/49867692/f1b4cfa5-81a0-4ca9-8367-c33aea776306)

**Comment by xpyjs** [comment]
参考 #40

**Comment by 2663272622** [comment]
> 参考 #40

已参考 #40 愿报错解决，现在出现新的报错 runtime-core.esm-bundler.js:221 Uncaught TypeError: Cannot read properties of null (reading 'isCE') 
目前版本信息
"@xpyjs/gantt": "^2.1.4"
"vue": "3.3.4",

代码如下：
`
<template> 
        <x-gantt
            data-id="id"
            :data="dataList"
            :ref="ganttRef"
            start-key="planStartTime"
            end-key="planEndTime"
        >
            <x-gantt-column label="标题" prop="name" />
            <x-gantt-column label="进度" prop="progress" />
            <x-gantt-column label="开始日期" prop="planStartTime" />
            <x-gantt-column label="结束日期" prop="planEndTime" />
    </x-gantt> 
</template>

<script setup lang='ts'>
    const dataList = ref([
        {
        id: 1660933075125125000,
        name: '小鸡快跑计划',
        projectId: 1,
        ganttDataType: 39,
        planStartTime: '2023-10-04 15:21:27',
        planEndTime: '2023-11-01 20:33:39',
        assign: 'anim Ut veniam elit aliquip',
        progress: 58,
        estimatedHours: 100,
        totalManHour: 84,
        remainingManHour: 93,
        status: 1,
        children: [
            {
            id: 1661169300083720200,
            parentId: 1660933075125125000,
            name: '孵鸡蛋',
            projectId: 1,
            ganttDataType: 2,
            planStartTime: '2023-11-04 15:21:27',
            planEndTime: '2023-12-01 20:33:39',
            assign: '陈小东',
            progress: 58,
            estimatedHours: 100,
            totalManHour: 84,
            remainingManHour: 93,
            status: 1,
            },
        ]
    }] )
</script>

<style lang="scss" scoped>

</style>`

**Comment by 2663272622** [comment]
`
<template> 
        <x-gantt
            data-id="id"
            :data="dataList"
            :ref="ganttRef"
            start-key="planStartTime"
            end-key="planEndTime"
        >
            <x-gantt-column label="标题" prop="name" />
            <x-gantt-column label="进度" prop="progress" />
            <x-gantt-column label="开始日期" prop="planStartTime" />
            <x-gantt-column label="结束日期" prop="planEndTime" />
    </x-gantt> 
</template>

<script setup lang='ts'>
    const dataList = ref([
        {
        id: 1660933075125125000,
        name: '小鸡快跑计划',
        projectId: 1,
        ganttDataType: 39,
        planStartTime: '2023-10-04 15:21:27',
        planEndTime: '2023-11-01 20:33:39',
        assign: 'anim Ut veniam elit aliquip',
        progress: 58,
        estimatedHours: 100,
        totalManHour: 84,
        remainingManHour: 93,
        status: 1,
        children: [
            {
            id: 1661169300083720200,
            parentId: 1660933075125125000,
            name: '孵鸡蛋',
            projectId: 1,
            ganttDataType: 2,
            planStartTime: '2023-11-04 15:21:27',
            planEndTime: '2023-12-01 20:33:39',
            assign: '陈小东',
            progress: 58,
            estimatedHours: 100,
            totalManHour: 84,
            remainingManHour: 93,
            status: 1,
            },
        ]
    }] )
</script>

<style lang="scss" scoped>

</style>`

**Comment by 2663272622** [comment]
已解决 是因为两个不同版本的vue导致的 现vue应该设置为与gantt 插件版本相同的即可解决
