### ISSUE TITLE
[BUG] 重新从后端获取数据时，二次滑动组件渲染有问题

### ISSUE THREAD

**Issue by Anan-X** [xpyjs/gantt#71]
<img width="525" alt="截屏2023-11-27 14 17 52" src="https://github.com/xpyjs/gantt/assets/64574687/c28a9bd5-6c43-40e1-94ff-925644f896ca">

<img width="476" alt="截屏2023-11-27 14 18 08" src="https://github.com/xpyjs/gantt/assets/64574687/886f6d08-cd0c-4a81-9bfe-2d2952c455da">

![截屏2023-11-27 14 18 21](https://github.com/xpyjs/gantt/assets/64574687/1a395439-920c-42d8-9d57-0aabda662427)

**Comment by xpyjs** [comment]
请详细描述
