### ISSUE TITLE
[BUG] 超过5个之后就无法渲染了

### ISSUE THREAD

**Issue by tinoyet** [xpyjs/gantt#72]
![111111111111111](https://github.com/xpyjs/gantt/assets/57076247/e559f532-c6e3-4af4-a93f-7a07b29c4aa0)
![22222222222222](https://github.com/xpyjs/gantt/assets/57076247/662c4895-ba84-48f0-9861-1a8b55e44244)

**Comment by xpyjs** [comment]
more code pls

**Comment by tinoyet** [comment]
![image](https://github.com/xpyjs/gantt/assets/57076247/4b68ea57-960d-47b6-a053-fabfc5b99271)
就写死的数据index和id都试过，6个无法全部渲染出来。

**Comment by xpyjs** [comment]
Check the validity of your code, then you can compare the difference between your code and  [demo](https://github.com/xpyjs/gantt/blob/master/demo/demo.vue)

**Comment by tinoyet** [comment]
在包裹插件的容器加高度就正常了。。。

**Comment by fengxc** [comment]
> 在包裹插件的容器加高度就正常了。。。

谢谢您的回复，不过我试了一下似乎没有看出来效果的样子，是我用的不对嘛？应该在哪里加啊？在外层div加也没看出来变化？
```
<div style="height:2000px">
			<x-gantt
				height="2000"
				ref="xgantt"
				data-id="id"
				:data="dataList"
				:links="linkList"
				start-key="planStartTimeShow"
				end-key="planEndTimeShow"
				locale="zh-CN"
				:unit="unit"
				:headerStyle="headerStyle"
				:body-style="bodyStyle"
			>
				<x-gantt-column prop="name" label="任务名称" width="240" />
				<x-gantt-column label="计划时间">
					<x-gantt-column label="计划开始" prop="planStartTime" date-format="YYYY-MM-DD" width="90" />
					<x-gantt-column label="计划结束" prop="planEndTime" date-format="YYYY-MM-DD" width="90" />
				</x-gantt-column>
				<x-gantt-slider bg-color="#000" :alignment="alignment" :move="false">
					<template v-slot:content="{ row, $index, level }">
						<div @click="click(row)" :style="colorByState(row)"></div>
					</template>
				</x-gantt-slider>
			</x-gantt>
		</div>
```

**Comment by jeremyjone** [comment]
> > 在包裹插件的容器加高度就正常了。。。
> 
> 谢谢您的回复，不过我试了一下似乎没有看出来效果的样子，是我用的不对嘛？应该在哪里加啊？在外层div加也没看出来变化？
> 
> ```
> <div style="height:2000px">
> 			<x-gantt
> 				height="2000"
> 				ref="xgantt"
> 				data-id="id"
> 				:data="dataList"
> 				:links="linkList"
> 				start-key="planStartTimeShow"
> 				end-key="planEndTimeShow"
> 				locale="zh-CN"
> 				:unit="unit"
> 				:headerStyle="headerStyle"
> 				:body-style="bodyStyle"
> 			>
> 				<x-gantt-column prop="name" label="任务名称" width="240" />
> 				<x-gantt-column label="计划时间">
> 					<x-gantt-column label="计划开始" prop="planStartTime" date-format="YYYY-MM-DD" width="90" />
> 					<x-gantt-column label="计划结束" prop="planEndTime" date-format="YYYY-MM-DD" width="90" />
> 				</x-gantt-column>
> 				<x-gantt-slider bg-color="#000" :alignment="alignment" :move="false">
> 					<template v-slot:content="{ row, $index, level }">
> 						<div @click="click(row)" :style="colorByState(row)"></div>
> 					</template>
> 				</x-gantt-slider>
> 			</x-gantt>
> 		</div>
> ```

加单把你代码复制跑了一下，把一些对象参数删掉了，比如 body-style，headerStyle，unit 等：

![Image](https://github.com/user-attachments/assets/a72c2899-34a0-4fc1-b7f4-6326c1f6b95c)

尝试修改你代码中外部 div 的 高度，将高度改为 200px 后，其他没有变：

![Image](https://github.com/user-attachments/assets/159f1b05-0a22-4979-ad07-a4de72e79a7a)

一切正常。


你检查一下你有没有其他样式注入，导致了问题

**Comment by fengxc** [comment]
> > > 在包裹插件的容器加高度就正常了。。。
> > 
> > 
> > 谢谢您的回复，不过我试了一下似乎没有看出来效果的样子，是我用的不对嘛？应该在哪里加啊？在外层div加也没看出来变化？
> > ```
> > <div style="height:2000px">
> > 			<x-gantt
> > 				height="2000"
> > 				ref="xgantt"
> > 				data-id="id"
> > 				:data="dataList"
> > 				:links="linkList"
> > 				start-key="planStartTimeShow"
> > 				end-key="planEndTimeShow"
> > 				locale="zh-CN"
> > 				:unit="unit"
> > 				:headerStyle="headerStyle"
> > 				:body-style="bodyStyle"
> > 			>
> > 				<x-gantt-column prop="name" label="任务名称" width="240" />
> > 				<x-gantt-column label="计划时间">
> > 					<x-gantt-column label="计划开始" prop="planStartTime" date-format="YYYY-MM-DD" width="90" />
> > 					<x-gantt-column label="计划结束" prop="planEndTime" date-format="YYYY-MM-DD" width="90" />
> > 				</x-gantt-column>
> > 				<x-gantt-slider bg-color="#000" :alignment="alignment" :move="false">
> > 					<template v-slot:content="{ row, $index, level }">
> > 						<div @click="click(row)" :style="colorByState(row)"></div>
> > 					</template>
> > 				</x-gantt-slider>
> > 			</x-gantt>
> > 		</div>
> > ```
> 
> 加单把你代码复制跑了一下，把一些对象参数删掉了，比如 body-style，headerStyle，unit 等：
> 
> ![Image](https://github.com/user-attachments/assets/a72c2899-34a0-4fc1-b7f4-6326c1f6b95c)
> 
> 尝试修改你代码中外部 div 的 高度，将高度改为 200px 后，其他没有变：
> 
> ![Image](https://github.com/user-attachments/assets/159f1b05-0a22-4979-ad07-a4de72e79a7a)
> 
> 一切正常。
> 
> 你检查一下你有没有其他样式注入，导致了问题

这个问题是这样的：下面那组数据是有children的，是好的，我们反复试过的，是只有在一个children都没有的时候是会有问题的，您试一下？比如这个
```
{
	"code": 200,
	"msg": "操作成功",
	"data": [
		{
			"id": "1901911776407347202",
			"parentId": "0",
			"weight": 1,
			"name": "一",
			"createTime": "2025-03-18 16:21:17",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:43:04",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 1,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901911925288361985",
			"parentId": "0",
			"weight": 2,
			"name": "二",
			"createTime": "2025-03-18 16:21:53",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:21:53",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 2,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901912073418596353",
			"parentId": "0",
			"weight": 3,
			"name": "三",
			"createTime": "2025-03-18 16:22:28",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:22:28",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 3,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901912217325166593",
			"parentId": "0",
			"weight": 4,
			"name": "四",
			"createTime": "2025-03-18 16:23:03",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:23:03",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 4,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901912389828501506",
			"parentId": "0",
			"weight": 5,
			"name": "五",
			"createTime": "2025-03-18 16:23:44",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:23:44",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 5,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901912528542523394",
			"parentId": "0",
			"weight": 6,
			"name": "六",
			"createTime": "2025-03-18 16:24:17",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:24:17",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 6,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901914368424304642",
			"parentId": "0",
			"weight": 7,
			"name": "七",
			"createTime": "2025-03-18 16:31:35",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:31:35",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 7,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901915378001666049",
			"parentId": "0",
			"weight": 8,
			"name": "1",
			"createTime": "2025-03-18 16:35:36",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:59:17",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "0.0",
			"realWorkload": "0.0",
			"taskOrder": 8,
			"projectId": "1901911171051839489",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "package",
			"progress": "0.00",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		},
		{
			"id": "1901914968234942465",
			"parentId": "0",
			"weight": 9,
			"name": "八",
			"createTime": "2025-03-18 16:33:58",
			"createUser": "1749703085984555010",
			"updateTime": "2025-03-18 16:59:17",
			"updateUser": "1749703085984555010",
			"acTypeId": "E",
			"status": "NEW",
			"planStartTime": "2025-03-10",
			"planEndTime": "2025-03-14",
			"planWorkload": "10",
			"taskOrder": 9,
			"projectId": "1901911171051839489",
			"principal": "1749708475577098242",
			"principalName": "普通成员",
			"auditor": "1749708475577098242",
			"auditorName": "普通成员",
			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
			"editByPrincipal": "false",
			"canAdd": "true",
			"canEdit": "true",
			"packType": "task",
			"isMilestone": "false",
			"isPm": true,
			"planStartTimeShow": "2025-03-10 00:00:00",
			"planEndTimeShow": "2025-03-14 23:59:59"
		}
	]
}
```

**Comment by jeremyjone** [comment]
> > > > 在包裹插件的容器加高度就正常了。。。
> > > 
> > > 
> > > 谢谢您的回复，不过我试了一下似乎没有看出来效果的样子，是我用的不对嘛？应该在哪里加啊？在外层div加也没看出来变化？
> > > ```
> > > <div style="height:2000px">
> > > 			<x-gantt
> > > 				height="2000"
> > > 				ref="xgantt"
> > > 				data-id="id"
> > > 				:data="dataList"
> > > 				:links="linkList"
> > > 				start-key="planStartTimeShow"
> > > 				end-key="planEndTimeShow"
> > > 				locale="zh-CN"
> > > 				:unit="unit"
> > > 				:headerStyle="headerStyle"
> > > 				:body-style="bodyStyle"
> > > 			>
> > > 				<x-gantt-column prop="name" label="任务名称" width="240" />
> > > 				<x-gantt-column label="计划时间">
> > > 					<x-gantt-column label="计划开始" prop="planStartTime" date-format="YYYY-MM-DD" width="90" />
> > > 					<x-gantt-column label="计划结束" prop="planEndTime" date-format="YYYY-MM-DD" width="90" />
> > > 				</x-gantt-column>
> > > 				<x-gantt-slider bg-color="#000" :alignment="alignment" :move="false">
> > > 					<template v-slot:content="{ row, $index, level }">
> > > 						<div @click="click(row)" :style="colorByState(row)"></div>
> > > 					</template>
> > > 				</x-gantt-slider>
> > > 			</x-gantt>
> > > 		</div>
> > > ```
> > 
> > 
> > 加单把你代码复制跑了一下，把一些对象参数删掉了，比如 body-style，headerStyle，unit 等：
> > ![Image](https://github.com/user-attachments/assets/a72c2899-34a0-4fc1-b7f4-6326c1f6b95c)
> > 尝试修改你代码中外部 div 的 高度，将高度改为 200px 后，其他没有变：
> > ![Image](https://github.com/user-attachments/assets/159f1b05-0a22-4979-ad07-a4de72e79a7a)
> > 一切正常。
> > 你检查一下你有没有其他样式注入，导致了问题
> 
> 这个问题是这样的：下面那组数据是有children的，是好的，我们反复试过的，是只有在一个children都没有的时候是会有问题的，您试一下？比如这个
> 
> ```
> {
> 	"code": 200,
> 	"msg": "操作成功",
> 	"data": [
> 		{
> 			"id": "1901911776407347202",
> 			"parentId": "0",
> 			"weight": 1,
> 			"name": "一",
> 			"createTime": "2025-03-18 16:21:17",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:43:04",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 1,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901911925288361985",
> 			"parentId": "0",
> 			"weight": 2,
> 			"name": "二",
> 			"createTime": "2025-03-18 16:21:53",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:21:53",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 2,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901912073418596353",
> 			"parentId": "0",
> 			"weight": 3,
> 			"name": "三",
> 			"createTime": "2025-03-18 16:22:28",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:22:28",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 3,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901912217325166593",
> 			"parentId": "0",
> 			"weight": 4,
> 			"name": "四",
> 			"createTime": "2025-03-18 16:23:03",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:23:03",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 4,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901912389828501506",
> 			"parentId": "0",
> 			"weight": 5,
> 			"name": "五",
> 			"createTime": "2025-03-18 16:23:44",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:23:44",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 5,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901912528542523394",
> 			"parentId": "0",
> 			"weight": 6,
> 			"name": "六",
> 			"createTime": "2025-03-18 16:24:17",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:24:17",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 6,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901914368424304642",
> 			"parentId": "0",
> 			"weight": 7,
> 			"name": "七",
> 			"createTime": "2025-03-18 16:31:35",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:31:35",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 7,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901915378001666049",
> 			"parentId": "0",
> 			"weight": 8,
> 			"name": "1",
> 			"createTime": "2025-03-18 16:35:36",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:59:17",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "0.0",
> 			"realWorkload": "0.0",
> 			"taskOrder": 8,
> 			"projectId": "1901911171051839489",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "package",
> 			"progress": "0.00",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		},
> 		{
> 			"id": "1901914968234942465",
> 			"parentId": "0",
> 			"weight": 9,
> 			"name": "八",
> 			"createTime": "2025-03-18 16:33:58",
> 			"createUser": "1749703085984555010",
> 			"updateTime": "2025-03-18 16:59:17",
> 			"updateUser": "1749703085984555010",
> 			"acTypeId": "E",
> 			"status": "NEW",
> 			"planStartTime": "2025-03-10",
> 			"planEndTime": "2025-03-14",
> 			"planWorkload": "10",
> 			"taskOrder": 9,
> 			"projectId": "1901911171051839489",
> 			"principal": "1749708475577098242",
> 			"principalName": "普通成员",
> 			"auditor": "1749708475577098242",
> 			"auditorName": "普通成员",
> 			"userJson": "[{\"userId\":\"1749708475577098242\",\"planWorkload\":10}]",
> 			"editByPrincipal": "false",
> 			"canAdd": "true",
> 			"canEdit": "true",
> 			"packType": "task",
> 			"isMilestone": "false",
> 			"isPm": true,
> 			"planStartTimeShow": "2025-03-10 00:00:00",
> 			"planEndTimeShow": "2025-03-14 23:59:59"
> 		}
> 	]
> }
> ```

简单试了一下，没有问题：

<img width="663" alt="Image" src="https://github.com/user-attachments/assets/69a789f8-a505-454f-94f4-7995ace1c6e6" />

```vue
<div style="height:2000px">
			<x-gantt
				height="2000"
				ref="xgantt"
				data-id="id"
				:data="dataList"
				start-key="planStartTimeShow"
				end-key="planEndTimeShow"
				locale="zh-CN"
			>
				<x-gantt-column prop="name" label="任务名称" width="240" />
				<x-gantt-column label="计划时间">
					<x-gantt-column label="计划开始" prop="planStartTime" date-format="YYYY-MM-DD" width="90" />
					<x-gantt-column label="计划结束" prop="planEndTime" date-format="YYYY-MM-DD" width="90" />
				</x-gantt-column>
				<x-gantt-slider bg-color="#000"  :move="false">
					<template v-slot:content="{ row, $index, level }">
						<div @click="click(row)"></div>
					</template>
				</x-gantt-slider>
			</x-gantt>
		</div>
```

我移除了其他参数。如果你还有问题，请检首先检查这些参数
