### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by petitepirogue** [xpyjs/gantt#75]
Bonjour pouvez-vous m'aider, j'ai rien qui s'affiche voici mon code, j'utilise yarn et vuejs 
@xpyjs/gantt@2.1.5
vue --version
@vue/cli 5.0.8
root@5c2cdcd3c3ef:/var/www/espace# yarn --version
1.22.19

voici mon code : 
<script>
import { reactive } from "vue";
import PageHeader from "@/components/page-header";
import Layout from "@/layouts/AppMain.vue";

import XGantt from "@xpyjs/gantt";
import "@xpyjs/gantt/dist/index.css";

export default {
  props: {
    reference: {
      type: String,
      required: true,
    },
  },
  data() {
    const dataList = [
      {
        index: 1,
        startDate: "2020-06-05",
        endDate: "2020-08-20",
        ttt: {
          a: "aaa",
          b: "bbb",
        },
        name: "mydata1",
        children: [], // children is required. If no child, empty array is ok.
      },
      {
        index: 2,
        startDate: "2020-07-07",
        endDate: "2020-09-11",
        ttt: {},
        name: "mydata2",
        children: [
          {
            index: 3,
            startDate: "2020-07-10",
            endDate: "2020-08-15",
            ttt: {
              a: "aaa",
            },
            name: "child1",
            children: [], // children is required. If no child, empty array is ok.
          },
        ],
      },
    ];
    const form = reactive({
      tasks: null,
    });
    return {
      form,
      dataList,
    };
  },
  methods: {},
  mounted() {},
  components: {
    Layout,
    PageHeader,
    XGantt,
  },
};
</script>

<template>
  <Layout>
    <PageHeader :title="$t('gantt_task')" :pageTitle="$t('tasks')" />
    <div style="background-color: white" id="index"></div>
    <XGantt data-id="index" :data="dataList" />
    <XGantt data-index="index" :data="dataList" />
  </Layout>
</template>

**Comment by xpyjs** [comment]
pls read bug template and follow that step report
