### ISSUE TITLE
[FEATURE]能否自定义甘特图的显示范围

### ISSUE THREAD

**Issue by RQD-china** [xpyjs/gantt#77]
**Is your feature request related to a problem? Please describe.**
例如我的甘特图上现在只有2月份有task，那我想要甘特图的表头只显示2月份的范围，但是现在会显示从1-3月的表头，导致很多部分其实是空白的。

**Describe the solution you'd like**
希望可以在根组件上增加两个属性来配置甘特图显示范围的起始和结束日期，或者现在的版本有没有什么办法能够控制甘特图表头的显示范围。

感谢！

**Comment by xpyjs** [comment]
不可以自定义。因为这样宽度变得不可控制，计算量增大会导致图表性能变差。毕竟这是元素绘制，不是canvas绘制的，理解。

**Comment by huoqingzhu** [comment]
希望可以增加  性能的优先级应该在功能之下  并且这配置应该是默认关闭的
