### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EdwardDZhang** [xpyjs/gantt#79]
在使用x-gantt-column时，最后一列的内容会错位到下一行去并且看不到
` <x-gantt data-id="index" :data="dataList" :body-style="bodyStyle" :border="0" :header-height="40"
      style="height: 100vh;" :header-style="headerStyle" :level-color="['#ffffff']" locale="zh-cn"
      primary-color="#F1F2FF" row-height="46" show-today>
      <x-gantt-column prop="index">
        <template #title>
          <div></div>
        </template>
      </x-gantt-column>
      <x-gantt-column prop="name">
        <template #title>
          任务
        </template>
        <template #default="{ row }">
          {{ row.name }}
        </template>
      </x-gantt-column>
      <x-gantt-column prop="status" label="状态" />
      <x-gantt-column prop="status" label="状态" /> // 这行的内容错位至下一行
    </x-gantt>`

**Comment by jeremyjone** [comment]
最小用例？
截图？
报什么错？

**Comment by EdwardDZhang** [comment]
![微信截图_20240328192504](https://github.com/xpyjs/gantt/assets/122089782/a9d19550-b19d-41c1-a10e-5cf06c7f7784)

**Comment by EdwardDZhang** [comment]
不是报错，是样式问题

**Comment by jeremyjone** [comment]
外部改了布局吗？给我一个最小复现代码

**Comment by EdwardDZhang** [comment]
抱歉 刚下班了，外观布局都是根据文档提供的修改的，没有写新的css



---Original---
From: "Jeremy ***@***.***&gt;
Date: Thu, Mar 28, 2024 19:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [xpyjs/gantt] [BUG] (Issue #79)




 
外部改了布局吗？给我一个最小复现代码

**Comment by jeremyjone** [comment]
有时间贴一个就行，我看一下。按文档应该不会出现此问题

**Comment by EdwardDZhang** [comment]
`
<template>
  <div>
    <x-gantt data-id="index" ref="ganttRef" :data="dataList" :body-style="bodyStyle" :border="0" :header-height="40"
      style="height: 100vh" :header-style="headerStyle" :level-color="['#ffffff']" locale="zh-cn"
      primary-color="#F1F2FF" row-height="46" show-today>
      <x-gantt-column prop="index">
        <template #title>
          <div></div>
        </template>
      </x-gantt-column>
      <x-gantt-column prop="name">
        <template #title> 任务 </template>
        <template #default="{ row }">
          {{ row.name }}
        </template>
      </x-gantt-column>
      <x-gantt-column prop="status" label="状态" width="150">
        <template #default="{ row }">
          <el-tag>{{ row.status }}</el-tag>
        </template>
      </x-gantt-column>
      <x-gantt-column prop="priority" label="优先级" width="150"></x-gantt-column>
    </x-gantt>
  </div>
</template>

<script lang="ts" setup>
import { onMounted, reactive, ref } from 'vue';
import type {
  XGanttComponent,
  XGanttColumnComponent,
  XGanttSliderComponent,
} from '@xpyjs/gantt';
const ganttRef = ref<XGanttComponent>();

const dataList = reactive<any>([]);

const bodyStyle = {
  bgColor: '#F8F8F8',
  hoverColor: '#e42411',
  selectColor: '#9ea2ff',
  textColor: '#999999',
};

const headerStyle = {
  bgColor: '#F1F2FF',
  textColor: '#333333',
};

const onAdd = () => {
  let index = 0;
  for (let i = 0; i < 10; i++) {
    dataList.push({
      index: ++index,
      name: `task${index}`,
      status: `status${index}`,
      priority: `priority${index}`,
      startDate: new Date(2024, 2, index),
      endDate: new Date(2024, 2, index + 5),
    });
  }
};

onMounted(() => {
  onAdd();
});
</script>`

**Comment by EdwardDZhang** [comment]
```
<template>
  <div>
    <x-gantt data-id="index" ref="ganttRef" :data="dataList" :body-style="bodyStyle" :border="0" :header-height="40"
      style="height: 100vh" :header-style="headerStyle" :level-color="['#ffffff']" locale="zh-cn"
      primary-color="#F1F2FF" row-height="46" show-today>
      <x-gantt-column prop="index">
        <template #title>
          <div></div>
        </template>
      </x-gantt-column>
      <x-gantt-column prop="name">
        <template #title> 任务 </template>
        <template #default="{ row }">
          {{ row.name }}
        </template>
      </x-gantt-column>
      <x-gantt-column prop="status" label="状态" width="150">
        <template #default="{ row }">
          <el-tag>{{ row.status }}</el-tag>
        </template>
      </x-gantt-column>
      <x-gantt-column prop="priority" label="优先级" width="150"></x-gantt-column>
    </x-gantt>
  </div>
</template>

<script lang="ts" setup>
import { onMounted, reactive, ref } from 'vue';
import type {
  XGanttComponent,
  XGanttColumnComponent,
  XGanttSliderComponent,
} from '@xpyjs/gantt';
const ganttRef = ref<XGanttComponent>();

const dataList = reactive<any>([]);

const bodyStyle = {
  bgColor: '#F8F8F8',
  hoverColor: '#e42411',
  selectColor: '#9ea2ff',
  textColor: '#999999',
};

const headerStyle = {
  bgColor: '#F1F2FF',
  textColor: '#333333',
};

const onAdd = () => {
  let index = 0;
  for (let i = 0; i < 10; i++) {
    dataList.push({
      index: ++index,
      name: `task${index}`,
      status: `status${index}`,
      priority: `priority${index}`,
      startDate: new Date(2024, 2, index),
      endDate: new Date(2024, 2, index + 5),
    });
  }
};

onMounted(() => {
  onAdd();
});
</script>
```

**Comment by jeremyjone** [comment]
![image](https://github.com/xpyjs/gantt/assets/37676231/8b264fcb-a87f-42e9-a5b3-2e6f6f5e87c8)

?
