### ISSUE TITLE
你好，请问能不能提供一个给行和列自定义class的方法[FEATURE]

### ISSUE THREAD

**Issue by Mr-city** [xpyjs/gantt#80]
你好，请问能不能提供一个给行和列自定义class的方法

**Comment by jeremyjone** [comment]
参考 [样式](https://xpyjs.github.io/gantt/docs/root.html#%E6%A0%B7%E5%BC%8F)

**Comment by Mr-city** [comment]
> Reference in new issue

有些特殊场景，比如我不是只加背景，而是给满足条件的某些行添加边框，或者其它的样式

**Comment by Mr-city** [comment]
> Reference in new issue

有些特殊场景，比如我不是只加背景，而是给满足条件的某些行添加边框，或者其它的样式

**Comment by jeremyjone** [comment]
给行或列直接添加样式，有可能会导致样式异常。建议可以考虑通过背景颜色区分。或者直接强制注入试试
