### ISSUE TITLE
更新x-gantt的data数据后，如果新数据的时间范围比上一条的数据的时间范围小，则时间轴仍然显示为上一次的时间范围[BUG]

### ISSUE THREAD

**Issue by nixgnail** [xpyjs/gantt#82]
**Describe the bug**
更新x-gantt的data数据后，如果新数据的时间范围比上一条的数据的时间范围小，则时间轴仍然显示为上一次的时间范围。反之则正常，是否可以提供一个刷新方法，非常感谢！
注：个人使用的vue3-v1版本。

**Comment by jeremyjone** [comment]
v1 如果更新所有时间会有卡顿，所以如果可以，请更新到 v2 即可，它会自动更新表头
