### ISSUE TITLE
[BUG]DEMO里面的组合式写法,表格全部是空,且目前我运用在项目里 也出现了表格渲染不出来的问题

### ISSUE THREAD

**Issue by RanRuan** [xpyjs/gantt#83]
**Describe the bug**
代码链接如下:
https://github.com/xpyjs/gantt/blob/master/demo/demo.vue
![image](https://github.com/xpyjs/gantt/assets/24689456/31ed0d98-e196-4335-b46f-01d536b3d91f)
![image](https://github.com/xpyjs/gantt/assets/24689456/b27494ba-552c-4369-905c-ed66fc934af3)

![image](https://github.com/xpyjs/gantt/assets/24689456/2ffd7cd6-830d-40cc-b159-3bc0514dec3b)

**Comment by xpyjs** [comment]
paste your code pls？

**Comment by RanRuan** [comment]
> paste your code pls？

[
[gantt-master.zip](https://github.com/xpyjs/gantt/files/14994458/gantt-master.zip)
](url)

**Comment by RanRuan** [comment]
> paste your code pls？
[gantt-master.zip](https://github.com/xpyjs/gantt/files/14994720/gantt-master.zip)

**Comment by RanRuan** [comment]
> paste minimum reproduction code, not zip. I can see it in here
// main.js
import { createApp } from 'vue';
import Gantt from "@xpyjs/gantt";
import "@xpyjs/gantt/dist/index.css";

createApp(App).use(Gantt).mount('#app');

// index.vue
<template>
  <div  class="gantt-wrap" v-loading="loading">
    <x-gantt
      data-id="index"
      :data="ganttData"
      header-height="48"
      :row-height="30"
    >
      <x-gantt-column label="事项" prop="name"></x-gantt-column>


    </x-gantt>
  </div>

</template>
import { reactive, ref, onMounted } from 'vue';
const ganttData = reactive([
{
    "index": 2,
    "name": "t1",
    "startDate": new Date('2022-01-24'),
    "endDate": new Date('2022-07-24'),
    "o": {
        "t1": "a",
        "t2": "b"
    },
    "children": [
        {
            "index": 51,
            "name": "sub-t51",
            "startDate": new Date('2022-01-27'),
            "endDate": new Date('2022-02-24'),
            "progress": 0.8,
            "o": {
                "t1": "a",
                "t2": "b"
            }
        },
        {
            "index": 52,
            "name": "sub-t52",
            "startDate":new Date('2022-03-27'),
            "endDate": new Date('2022-04-27'),
            "progress": 0.5,
            "o": {
                "t1": "a",
                "t2": "b"
            },
            "children": [
                {
                    "index": 53,
                    "name": "sub-sub-t53",
                    "startDate": new Date('2022-06-27'),
                    "endDate": new Date('2022-06-28'),
                    "progress": 0.3333333333,
                    "o": {
                        "t1": "a",
                        "t2": "b"
                    }
                }
            ]
        }
    ]
},
]);

**Comment by RanRuan** [comment]
> paste minimum reproduction code, not zip. I can see it in here

`
<template>
  <div  class="gantt-wrap" >
    <x-gantt
      data-id="index"
      :data="ganttData"
      header-height="48"
      :row-height="30"
    >
      <x-gantt-column label="事项" prop="name"></x-gantt-column>
    </x-gantt>
  </div>

</template>

<script lang="ts" setup>
import { reactive, ref, onMounted } from 'vue';

const ganttData = reactive([
{
    "index": 2,
    "name": "t1",
    "startDate": new Date('2022-01-24'),
    "endDate": new Date('2022-07-24'),
    "o": {
        "t1": "a",
        "t2": "b"
    },
    "children": [
        {
            "index": 51,
            "name": "sub-t51",
            "startDate": new Date('2022-01-27'),
            "endDate": new Date('2022-02-24'),
            "progress": 0.8,
            "o": {
                "t1": "a",
                "t2": "b"
            }
        },
        {
            "index": 52,
            "name": "sub-t52",
            "startDate":new Date('2022-03-27'),
            "endDate": new Date('2022-04-27'),
            "progress": 0.5,
            "o": {
                "t1": "a",
                "t2": "b"
            },
            "children": [
                {
                    "index": 53,
                    "name": "sub-sub-t53",
                    "startDate": new Date('2022-06-27'),
                    "endDate": new Date('2022-06-28'),
                    "progress": 0.3333333333,
                    "o": {
                        "t1": "a",
                        "t2": "b"
                    }
                }
            ]
        }
    ]
},

]);

</script>
`

**Comment by RanRuan** [comment]
> paste minimum reproduction code, not zip. I can see it in here

``
<template>
  <div  class="gantt-wrap" >
    <x-gantt
      data-id="index"
      :data="ganttData"
      header-height="48"
      :row-height="30"
    >
      <x-gantt-column label="事项" prop="name"></x-gantt-column>
    </x-gantt>
  </div>

</template>

<script lang="ts" setup>
import { reactive, ref, onMounted } from 'vue';

const ganttData = reactive([
{
    "index": 2,
    "name": "t1",
    "startDate": new Date('2022-01-24'),
    "endDate": new Date('2022-07-24'),
    "o": {
        "t1": "a",
        "t2": "b"
    },
    "children": [
        {
            "index": 51,
            "name": "sub-t51",
            "startDate": new Date('2022-01-27'),
            "endDate": new Date('2022-02-24'),
            "progress": 0.8,
            "o": {
                "t1": "a",
                "t2": "b"
            }
        },
        {
            "index": 52,
            "name": "sub-t52",
            "startDate":new Date('2022-03-27'),
            "endDate": new Date('2022-04-27'),
            "progress": 0.5,
            "o": {
                "t1": "a",
                "t2": "b"
            },
            "children": [
                {
                    "index": 53,
                    "name": "sub-sub-t53",
                    "startDate": new Date('2022-06-27'),
                    "endDate": new Date('2022-06-28'),
                    "progress": 0.3333333333,
                    "o": {
                        "t1": "a",
                        "t2": "b"
                    }
                }
            ]
        }
    ]
},

]);

</script>

<style>
.gantt-wrap {
  width: 100%; 
  height: 600px; 
  padding: 0 8px
}

.slider-level-one {
  background-color: #123456;
  height: 5px;
  position: relative;
}

.slider-level-one::before {
  content: '';
  position: absolute;
  left: 0px;
  height: 0px;
  width: 0px;
  border-style: solid;
  border-left-width: 0px;
  border-right-width: 5px;
  border-top-width: 5px;
  border-bottom-width: 10px;
  border-left-color: transparent;
  border-top-color: transparent;
  border-bottom-color: transparent;
  border-right-color: #123456;
}

.slider-level-one::after {
  content: '';
  position: absolute;
  right: 0px;
  height: 0px;
  width: 0px;
  border-style: solid;
  border-left-width: 5px;
  border-right-width: 0px;
  border-top-width: 5px;
  border-bottom-width: 10px;
  border-left-color: #123456;
  border-top-color: #123456;
  border-bottom-color: transparent;
  border-right-color: transparent;
}

.tip-text {
  margin-top: 1rem;
  font-size: 1.5rem;
  color: red;
}

.code-link {
  margin-top: 1rem;
  color: red;
  text-decoration: none;
}

.test-class {
  color: red;
}
</style>
``

**Comment by RanRuan** [comment]
<template>
  <div  class="gantt-wrap" >
    <x-gantt
      data-id="index"
      :data="ganttData"
      header-height="48"
      :row-height="30"
    >
      <x-gantt-column label="事项" prop="name"></x-gantt-column>
    </x-gantt>
  </div>
</template>

`
import { reactive, ref, onMounted } from 'vue';
const ganttData = reactive([
{
    "index": 2,
    "name": "t1",
    "startDate": new Date('2022-01-24'),
    "endDate": new Date('2022-07-24'),
    "o": {
        "t1": "a",
        "t2": "b"
    },
    "children": [
        {
            "index": 51,
            "name": "sub-t51",
            "startDate": new Date('2022-01-27'),
            "endDate": new Date('2022-02-24'),
            "progress": 0.8,
            "o": {
                "t1": "a",
                "t2": "b"
            }
        },
        {
            "index": 52,
            "name": "sub-t52",
            "startDate":new Date('2022-03-27'),
            "endDate": new Date('2022-04-27'),
            "progress": 0.5,
            "o": {
                "t1": "a",
                "t2": "b"
            },
            "children": [
                {
                    "index": 53,
                    "name": "sub-sub-t53",
                    "startDate": new Date('2022-06-27'),
                    "endDate": new Date('2022-06-28'),
                    "progress": 0.3333333333,
                    "o": {
                        "t1": "a",
                        "t2": "b"
                    }
                }
            ]
        }
    ]
}

]);`

**Comment by RanRuan** [comment]
> paste minimum reproduction code, not zip. I can see it in here

<template>
  <div  class="gantt-wrap" >
    <x-gantt
      data-id="index"
      :data="ganttData"
      header-height="48"
      :row-height="30"
    >
      <x-gantt-column label="事项" prop="name"></x-gantt-column>
    </x-gantt>
  </div>
</template>

**Comment by RanRuan** [comment]
> paste minimum reproduction code, not zip. I can see it in here

When the length of ganttData is equal to 1, it displays blank.
![image](https://github.com/xpyjs/gantt/assets/24689456/a2d4c516-3b69-42d0-b467-515463953219)

**Comment by RanRuan** [comment]
> paste minimum reproduction code, not zip. I can see it in here

I found in the source code src\composables\useInView.ts，line 14 ：
```js
  // 预加载条数
  const preload = 5;

**Comment by jeremyjone** [comment]
看到了代码，运行了一下，结果如下图：

![image](https://github.com/xpyjs/gantt/assets/37676231/391db495-a3ea-4cea-849d-af0223f0d40d)

并没有你说的问题。

1、检查你的代码
2、确保已经升级到最新版本


> > paste minimum reproduction code, not zip. I can see it in here
> 
> I found in the source code src\composables\useInView.ts，line 14 ：
> 
> ```js
>   // 预加载条数
>   const preload = 5;
> ```

这个预加载是为了防止滚动时出现白屏，和你说的问题没有关系
