### ISSUE TITLE
添加ellipsis属性之后 文字超出只显示了省略号， 期待能支持鼠标滑过显示全量文字信息

### ISSUE THREAD

**Issue by zzz0908** [xpyjs/gantt#84]
添加ellipsis属性之后 文字超出只显示了省略号， 期待能支持鼠标滑过显示全量文字信息

**Comment by jeremyjone** [comment]
> 添加ellipsis属性之后 文字超出只显示了省略号， 期待能支持鼠标滑过显示全量文字信息

这个需要自己通过插槽控制一下。因为我不清楚使用者需要什么样的提示框。
