### ISSUE TITLE
如果数据列表日期为空，那么渲染为报错，为空我传的null[BUG]

### ISSUE THREAD

**Issue by Mr-city** [xpyjs/gantt#85]
![image](https://github.com/xpyjs/gantt/assets/28587958/4534fffa-2dad-4654-bf92-c546d43deef5)

**Comment by Mr-city** [comment]
第一条数据日期为空，并且没有子集

**Comment by jeremyjone** [comment]
没有日期当然为空。。。

**Comment by Mr-city** [comment]
> 没有日期当然为空。。。

主要我的根节点日期可能为空，表头渲染就会错

**Comment by jeremyjone** [comment]
> > 没有日期当然为空。。。
> 
> 主要我的业务根节点日期可能为空，表头渲染就会错，子节点有数据，日期是根据选择页面来选择的

你可以将计划日期填入。

如果是为空，可以考虑填一个0天的宽度，或者将当前slider的可视display置为none，或者样式置为透明。

因为如果父级为空，可能会影响子级的滑动，所以需要填一个。

**Comment by Mr-city** [comment]
> > > 没有日期当然为空。。。
> > 
> > 
> > 主要我的业务根节点日期可能为空，表头渲染就会错，子节点有数据，日期是根据选择页面来选择的
> 
> 你可以将计划日期填入。
> 
> 如果是为空，可以考虑填一个0天的宽度，或者将当前slider的可视display置为none，或者样式置为透明。
> 
> 因为如果父级为空，可能会影响子级的滑动，所以需要填一个。

好的，麻烦 还有问题，
![image](https://github.com/xpyjs/gantt/assets/28587958/df56ee3c-8bf9-4927-89d4-aa16b7c12fcb)
差一天对不齐 这个怎么处理了

**Comment by jeremyjone** [comment]
> > > > 没有日期当然为空。。。
> > > 
> > > 
> > > 主要我的业务根节点日期可能为空，表头渲染就会错，子节点有数据，日期是根据选择页面来选择的
> > 
> > 你可以将计划日期填入。
> > 
> > 如果是为空，可以考虑填一个0天的宽度，或者将当前slider的可视display置为none，或者样式置为透明。
> > 
> > 因为如果父级为空，可能会影响子级的滑动，所以需要填一个。
> 
> 好的，麻烦 还有问题，
> ![image](https://github.com/xpyjs/gantt/assets/28587958/df56ee3c-8bf9-4927-89d4-aa16b7c12fcb)
> 差一天对不齐 这个怎么处理了

没看明白，是周末啊？
