### ISSUE TITLE
进度条跟最终日期差一天[BUG]

### ISSUE THREAD

**Issue by Mr-city** [xpyjs/gantt#86]
![image](https://github.com/xpyjs/gantt/assets/28587958/902febdd-b76a-4056-987e-656394b1066b)

最终日期是25号，但是显示在24号上面

**Comment by jeremyjone** [comment]
一定是你日期为25号0点，那么slider一定结尾在24-25的位置上

**Comment by Mr-city** [comment]
> 一定是你日期为25号0点，那么slider一定结尾在24-25的位置上

设置 25号23：59：59 还是在24号上面

**Comment by jeremyjone** [comment]
> > 一定是你日期为25号0点，那么slider一定结尾在24-25的位置上
> 
> 设置 25号23：59：59 还是在24号上面

发一个最小复现代码，我看一下
