### ISSUE TITLE
[FEATURE]  table 自动调整列宽

### ISSUE THREAD

**Issue by tesla-cat** [xpyjs/gantt#88]
## 问题 1： table 自动调整列宽

- table 能不能用 th, td 那些渲染
- 这样的话每一列就能自动调整宽度， 不用手动设置
- 只需要设置整个 table 的 width, 然后加一个 overflow-x: scroll 即可

## 问题 2： 联系方式

- 能否添加您的联系方式

## 问题 3： 原理教程或指个学习方向

- 能否出一个教程讲解一下这个库的实现原理: 虚拟渲染， 同步滚动，任务渲染，连接线渲染，日期转坐标等等
- 我自己之前想写gantt, 但是发现这跟设计一般的用户界面完全不同 (我是自学前端的)

**Comment by jeremyjone** [comment]
因为甘特图不同于table，如果自动宽度的话，其实有一个很大的问题，就是右侧滑动部分显示多少。其次，其实自动宽度的意义在甘特图上并不大，因为表格部分应该为辅助，顶多3-4列是合理的展示，右侧日期滑动部分才是重点部分，否则直接使用表格不就好了么。

基于上面的思路，所以我设计了可拖拽列宽式的表头，以适应类似部分场景，一般情况都可以满足。

---

我这个其实没啥可说的，挺简单的，就是一个虚拟滚动机制，一个简易diff，看一下源码可能写的比我这个好哈

**Comment by tesla-cat** [comment]
因为我表格部分需要做的比较复杂， 大概这个样子

![image](https://github.com/xpyjs/gantt/assets/28215638/93046b77-6dd8-474f-b311-606dc8ad825c)
