### ISSUE TITLE
[BUG] 在线文档地址挂了

### ISSUE THREAD

**Issue by Lnncoco** [xpyjs/gantt#92]
[docs.xiaopangying.com/gantt/](https://docs.xiaopangying.com/gantt/)  在线文档地址挂了 404 Not Found

**Comment by jeremyjone** [comment]
已恢复

**Comment by Lnncoco** [comment]
奇怪  我这里还是展示 
404 Not Found
nginx

**Comment by jeremyjone** [comment]
重启了一下nginx，你再试一下。如果不行，直接使用 [这个地址](https://xpyjs.github.io/gantt/docs/)

**Comment by Lnncoco** [comment]
https://docs.xiaopangying.com/gantt/  这个依然不行
https://xpyjs.github.io/gantt/docs/  这个可用  感谢
