### ISSUE TITLE
[BUG] 拖动子级时父级不会跟随增长

### ISSUE THREAD

**Issue by Lnncoco** [xpyjs/gantt#93]
拖动时，如果节点比较小，会点到左右两端，这时候能移动节点，往点击端点的反方向拖动，可以超过父级长度，并且父级不会增长。
如果此时按正常拖动，父级会正常补长。

初始状态
![image](https://github.com/xpyjs/gantt/assets/57341815/bb9b81d3-98c6-4d86-9965-7a41cf86a7fe)

拖动后状态
![image](https://github.com/xpyjs/gantt/assets/57341815/3ab151a4-aaa0-48c0-9ed6-48522a80b2e1)

**Comment by jeremyjone** [comment]
code pls

**Comment by Lnncoco** [comment]
> code pls

[xgantt-bug-93](https://codesandbox.io/p/devbox/xgantt-bug-93-7lgflh?file=%2Fsrc%2Fcomponents%2FXGantt.vue%3A7%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw0elot500073j6ipzr2pjrg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw0elot300023j6iqj9jtly0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw0elot300043j6ik6foevas%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw0elot400063j6ifv3zhobs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw0elot300023j6iqj9jtly0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw0elot100013j6ijumgpekz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw0ewguc00023j6ibzhh7wqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FXGantt.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw0elot300023j6iqj9jtly0%2522%252C%2522activeTabId%2522%253A%2522clw0ewguc00023j6ibzhh7wqa%2522%257D%252C%2522clw0elot400063j6ifv3zhobs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw0elot400053j6iw8exzcdf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw0elot400063j6ifv3zhobs%2522%252C%2522activeTabId%2522%253A%2522clw0elot400053j6iw8exzcdf%2522%257D%252C%2522clw0elot300043j6ik6foevas%2522%253A%257B%2522id%2522%253A%2522clw0elot300043j6ik6foevas%2522%252C%2522activeTabId%2522%253A%2522clw0elot300033j6iidflnknr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw0elot300033j6iidflnknr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clw0emu7h006o3j6i3msyuo3c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clw0emz1i000tdahuhyikhkqm%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by jeremyjone** [comment]
update to v2.1.6
