### ISSUE TITLE
[BUG] 组件与vue版本不兼容导致不能运行

### ISSUE THREAD

**Issue by Sune0** [xpyjs/gantt#94]
报错 Cannot read properties of null (reading 'isCE')
因为项目不能更改vue版本，如何实现在不更改项目vue版本的前提下，使得组件兼容当前v3.3.4版本
![1716805361466](https://github.com/xpyjs/gantt/assets/82764446/e0a9f683-c2a9-4ff0-a8a4-8337ed4e0da9)

**Comment by jeremyjone** [comment]
不兼容应该考虑升级，因为内部使用了对应的特性

**Comment by Sune0** [comment]
但是问题是项目的版本比组件版本要高，项目版本是3.3.4 我看组件是3.2.47



***@***.***
 
发件人： Jeremy Jone
发送时间： 2024-05-27 18:31
收件人： xpyjs/gantt
抄送： Sune0; Author
主题： Re: [xpyjs/gantt] [BUG] 组件与vue版本不兼容导致不能运行 (Issue #94)
不兼容应该考虑升级，因为内部使用了对应的特性

**Comment by Sune0** [comment]
如果是项目版本比组件版本高引发的需要怎么解决？我看组件的版本是3.2.47但是我项目的版本是3.3.4



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jeremy Jone ***@***.***&gt;
发送时间: 2024年5月27日 18:31
收件人: xpyjs/gantt ***@***.***&gt;
抄送: Sune0 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xpyjs/gantt] [BUG] 组件与vue版本不兼容导致不能运行 (Issue #94)





 
不兼容应该考虑升级，因为内部使用了对应的特性

**Comment by jeremyjone** [comment]
isCE是你本地参数？跟版本没有关系

**Comment by Sune0** [comment]
我看#70也有这个问题，我通过降低项目的vue版本到3.2.47不会出现isCE错误，但是项目版本降低会引发其他组件的问题

**Comment by Sune0** [comment]
只要把vue版本锁死在3.3.4就会出现这个问题，我开了个空项目单独引入也会有这个问题 :(

**Comment by Sune0** [comment]
问题解决了 在vite.config.ts文件中resolve对象，加入`dedupe: ['vue']`可以解决问题，通过查看资料，应该是组件依赖的vue版本不一致导致的报错 :)
