### ISSUE TITLE
[FEATURE]: 添加同一行显示多个色块的功能；添加跨行拖拽功能；

### ISSUE THREAD

**Issue by XuPengGuan** [xpyjs/gantt#95]
您好，我说明一下在使用的时候的缺陷：
    1、一行只能有一个色块数据，希望能有多个
    2、现在只能左右拖动，希望能添加上下跨行拖动的功能
    3、有连线时希望能够拖动联动，就是拖动连线的开始节点，那么结束节点也会跟着移动，类似  https://gantt-schedule-timeline-calendar.neuronet.io/gstc/examples/complex-1/index.html 的拖动效果
    
最后，深知开源不易，但是还是希望作者大大能够看到这些问题，继续完善

**Comment by jeremyjone** [comment]
1. 参考#45
2. 支持行拖拽，看一下文档
3. 连线目前是不会固定两端间距的，可以考虑，但是不好说哈
