### ISSUE TITLE
[FEATURE]右侧甘特图右侧增加最小移动单位为月份和周

### ISSUE THREAD

**Issue by Sune0** [xpyjs/gantt#96]
现在右侧显示出来可以最小月份，但是操作层面还是通过天来操作，希望每周或每月为一个移动单位

**Comment by Sune0** [comment]
move-by-unit属性

**Comment by jeremyjone** [comment]
显示是为了获取更长展示区间。而拖动最大以天，是为了方便实际调度。这个可能不太好调整。默认都是以天最大单位，再大有可能不满足需求。

**Comment by Sune0** [comment]
了解，感谢回复~
