### ISSUE TITLE
[FEATURE]能否实现通过data数组加入color字段，控制每条滑块的颜色

### ISSUE THREAD

**Issue by Sune0** [xpyjs/gantt#97]
能否实现通过data数组加入color字段，控制每条滑块的颜色

**Comment by jeremyjone** [comment]
参考 [文档](https://xpyjs.github.io/gantt/docs/slider.html#%E5%9F%BA%E7%A1%80%E4%BD%BF%E7%94%A8)

我认为你可以需要动态颜色。甘特图不会处理data里的数据，除了最基础的内容。


两个方案：
1. 如果仅仅是按层级或者有规律的颜色，可以通过自定义对象添加到bgColor属性中
2. 可以通过插槽，自定义样式

**Comment by Sune0** [comment]
1. bgColor我看文档只接受string类型参数
2. 插槽能改变精度条样式，但是左右两边的拖动块改不了，如下图
![image](https://github.com/xpyjs/gantt/assets/82764446/6d3cf96a-6148-4f83-a0b7-a9c2a720bd4b)

**Comment by jeremyjone** [comment]
也有对应的插槽呀

**Comment by Sune0** [comment]
好的，找到了，感谢回复

**Comment by Delicatesparks** [comment]
> 1. bgColor我看文档只接受string类型参数
> 2. 插槽能改变精度条样式，但是左右两边的拖动块改不了，如下图
>    ![image](https://private-user-images.githubusercontent.com/82764446/335034574-6d3cf96a-6148-4f83-a0b7-a9c2a720bd4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzgxNDMsIm5iZiI6MTcyMjgzNzg0MywicGF0aCI6Ii84Mjc2NDQ0Ni8zMzUwMzQ1NzQtNmQzY2Y5NmEtNjE0OC00ZjgzLWEwYjctYTljMmE3MjBiZDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA2MDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMGMwYzVmNjliYjJkZjA5ZDMyYjUyYjEwY2QzYzkxODlkMDhjZmY2ZjMwMGZjM2Y1NDYyMGFiYjgxYjg2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4is3jKcVlp2E8rVVB9jwmGg-ogVKOcDda1uZq3xln0w)

请问你最后怎么解决改颜色的 可以给段代码吗 @Sune0
