### ISSUE TITLE
[BUG]结束时间对应的滑块最末端位置长度不正确

### ISSUE THREAD

**Issue by Sune0** [xpyjs/gantt#98]
下面这个，我个人认为按天为单位拖动滑块时，是否结束时间是28的时候，要把28当天覆盖掉？

![image](https://github.com/xpyjs/gantt/assets/82764446/a3725e90-f392-4256-a541-b431ce804d45)

**Comment by jeremyjone** [comment]
内部计算永远以秒计算。覆盖28号，会改变data中的数据。你应该把时间写成28号23点59分59秒

why：
因为按天移动只是一个临时操作，用户有可能修改行为模式，此时改变data的时间是不合适的

**Comment by Sune0** [comment]
但是拖动当右边滑块的时候，滑块覆盖到27号，但是结束世界已经显示到28号了，右边滑块拖动是否应该设置成27号23点59分59秒呢
