### ISSUE TITLE
[BUG]当设置linked-resize="true"时，当父任务拖动时，原本无时间轴的子任务会自动增加一个时间

### ISSUE THREAD

**Issue by Sune0** [xpyjs/gantt#99]
![image](https://github.com/xpyjs/gantt/assets/82764446/ae7cb83b-bffb-44c6-93a9-6d4d6fa40520)
![image](https://github.com/xpyjs/gantt/assets/82764446/8c8868d6-ea80-42bb-8067-180a261bc2e5)

**Comment by jeremyjone** [comment]
你都联动了，它难道不应该实时更新子任务么。。。

**Comment by Sune0** [comment]
但是我的理解是，如果子任务为空，不应该触发子任务更新，不然的话本来子任务本来是无时间的，凭空加个时间是有问题的吧
